version: "3.9"

services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "db_time_tracker"
      POSTGRES_USER: "pguser"
      POSTGRES_PASSWORD: "pgpwd"
    volumes:
      - ./create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    ports:
      - "5432:5432"