/*
 * People info
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"
	"os"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	sw "github.com/KseniiaTD/time-tracker/ext_api/ext-server/go"
	"github.com/joho/godotenv"
)

func main() {
	err := godotenv.Load("../../config.env")
	if err != nil {
		log.Fatal(err)
	}

	router := sw.NewRouter()

	port := os.Getenv("EXTERNAL_SERVICE_PORT")
	log.Printf("Server started on port " + port)
	log.Fatal(http.ListenAndServe(":"+port, router))
}
